FROM rust-base 

# run these in separate steps, so we can cache MSVC between all images.
COPY script/windows/msvc/*.sh /
RUN /msvc-wine.sh 

COPY script/windows/wine.sh /
RUN /wine.sh

# need windows-style perl for paths
COPY script/perl.sh /
RUN /perl.sh

ARG ARCH=x64
RUN /msvc-wine-symlink.sh $ARCH

RUN mkdir -p /usr/lib/binfmt-support/ && \
    rm -f /usr/lib/binfmt-support/run-detectors /usr/bin/run-detectors && \
    ln -s /usr/bin/wine /usr/lib/binfmt-support/run-detectors && \
    ln -s /usr/bin/wine /usr/bin/run-detectors

ENTRYPOINT ["/msvc-windows-entry.sh"]

ENV CROSS_SYSROOT=/opt/msvc/vc/tools/msvc/latest
ENV CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_LINKER=link.exe \
    CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_RUNNER=wine \
    CC_x86_64_pc_windows_msvc=cl.exe \
    CXX_x86_64_pc_windows_msvc=cl.exe \
    PATH=/opt/msvc/bin/$ARCH:$PATH \
    WINEPATH="$WINEPATH;C:/windows/syswow64;C:/windows/system32;/opt/msvc/bin/$ARCH" \
    VSINSTALLDIR="/opt/msvc" \
    VCINSTALLDIR="/opt/msvc/vc" \
    VSCMD_ARG_TGT_ARCH=$ARCH

WORKDIR /root/src
RUN rustup target add x86_64-pc-windows-msvc
